# Generated by Django 5.0.6 on 2024-06-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='file_hash',
            field=models.CharField(default='', max_length=512),
        ),
    ]
