# Generated by Django 5.0.6 on 2024-06-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resume_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='cover_letter_file',
            field=models.FileField(blank=True, null=True, upload_to='cover_letters/'),
        ),
        migrations.AddField(
            model_name='resume',
            name='cover_letter_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
