# Generated by Django 5.0.6 on 2024-06-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume_address_resume_cover_letter_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='cover_letter_file',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='cover_letter_text',
        ),
    ]
