# Generated by Django 5.0.6 on 2024-07-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_remove_resume_cover_letter_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
